### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by css277** [luiserrador/IndVertSeg_VerSe#2]
Hello, I have a bug while trying to use your code,326 lines in utils/data_utilities.py file，ValueError: Not all axis codes [16, 42.0, 78.0, 57.0] in label set ['L', 'R', 'P', 'A', 'I', 'S', None].How do I fix this? Looking forward to your reply，thank you very much

**Comment by luiserrador** [comment]
Hy!! Thanks for opening this issue.
I'll go through it asap.
Nonetheless, check if your nibabel is correct and if it solves your issue, it has to be the version 3.2.1 according to the 'requirements.txt'
I'll update you as soon as I check this issue.

**Comment by luiserrador** [comment]
Hello! Everything working fine here.

I added 1 validation and 1 training volume of each dataset (VerSe19 and VerSe20) to be used as test. My suggestion is to test everything using this data (I mean, update your project with this data and skip the step of running the *get_verse_data.py* script).

Once everything is going well, you can then download all the data, by following the steps described [here](https://github.com/luiserrador/IndVertSeg_VerSe/blob/master/README.md).

I'm pretty sure your problem is related to the nibabel version! I'll keep this issue open until we manage to fix it for you.

Looking forward to hear from you.

**Comment by css277** [comment]
Hello, thank you very much for your answer, I successfully solved this problem, the dataset I downloaded is  MICCAI challenge data structure that does not have direction information such as ["P", "I", "R"], but you are using subject based data structure, which causes me to not successfully read.

**Comment by luiserrador** [comment]
Makes sense! I thought you had downloaded the dataset from get_verse_data.py. Glad to know that it is solved 👍
